# ---- Build Stage ----
    FROM node:18-alpine AS build
    WORKDIR /app
    
    # Pass build-time argument
    ARG VITE_API_URL
    ENV VITE_API_URL=$VITE_API_URL
    
    COPY package*.json ./
    RUN npm install
    
    COPY . .
    RUN npm run build
    
    # ---- Production Stage ----
    FROM nginx:alpine
    WORKDIR /usr/share/nginx/html
    RUN rm -rf ./*
    COPY --from=build /app/dist .
    EXPOSE 80
    CMD ["nginx", "-g", "daemon off;"]